apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: slack-secret-reader
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["slack-webhook"]
  verbs: ["get"]
