apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd

spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: first-app
    helm:
      parameters:
      - name: ingress.hosts[0].host
        value: argo-app.k1s-1.sa
      - name: ingress.hosts[0].paths[0].path
        value: /
      - name: ingress.hosts[0].paths[0].pathType
        value: ImplementationSpecific
    repoURL: https://andrewbulah.github.io/helm/
    targetRevision: 0.1.0
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
